[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/success/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true